name: 'dbt_proj'
version: '1.0.0'
profile: 'dbt_proj'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_proj:
    data-lake:
      +materialized: view
      +schema: DL_TAXI
    staging:
      +materialized: view
      +schema: STG_TAXI
    warehouse:
      +materialized: table
      +schema: DWH_TAXI
    marts:
      finance:
        +materialized: view
        +schema: MART_FINANCE
      operations:
        +materialized: view
        +schema: MART_OPS
      analytics:
        +materialized: view
        +schema: MART_ANALYTICS
      